name: agop
description: "An AI powered farming mobile application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  simple_icons: ^14.6.1
  http: ^1.6.0
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Moved here because it is a development tool
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Make sure your logo file is explicitly accessible if needed,
    # though the icon tool reads it directly from the path below.
    - assets/images/app_icon.png

  fonts:
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader.ttf
    - family: InstrumentSerif
      fonts:
        - asset: assets/fonts/InstrumentSerif.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21